puts "The students of my cohort at Makers Academy"
puts "-------------------------------------------"
puts "Kieran Goodacre"
puts "Emily Sas"
puts "India Dearlove"
puts "Jacob Mitchinson"
puts "Marc Inwal"
puts "Andy Newman"
puts "Richard Ighodaro"
puts "Sanda Golcea"
puts "Ptolemy Barnes"
puts "Steph Oldcorn"
puts "Huy Le"
puts "Marcus de Wilde"
puts "Matteo Manzo"
puts "Luke Clewlow"
puts "Oliver Lucas"
puts "Jack Rubio"
puts "David Blake"
puts "Charlie Walsh"
puts "Jin Dai"
puts "Gus Powell"
puts "Jake Alvarez"
puts "Hannah Carney"
puts "Bibiana Cristofol"